version: '3'

services:
  csvserver:
    restart: always   
    image: infracloudio/csvserver
    container_name: csvserver
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile.csv:/csvserver/inputdata

  prometheus:
    restart: always
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
